default:
  Input:
    Discovery dataset name: "ND_HFD_merged"
    Expression matrix: "/gpfsdata/home/renyixiang/SRTP/ecotyper/ND_HFD_merged/expr_matrix_filtered.txt.gz"
    Annotation file: "/gpfsdata/home/renyixiang/SRTP/ecotyper/ND_HFD_merged/annotation_filtered_merged_fixed.txt"
    Annotation file column to scale by: NULL
    Annotation file column(s) to plot: ["Sample"]

  Output:
    Output folder: "/gpfsdata/home/renyixiang/SRTP/ecotyper/ND_HFD_mergedOutput"

  Pipeline settings:
    Pipeline steps to skip: []
    Filter genes: "cell type specific"
    Number of threads: 10
    Number of NMF restarts: 50
    Maximum number of states per cell type: 20
    Cophenetic coefficient cutoff: 0.975
    Jaccard matrix p-value cutoff: 1
    Minimum number of states in ecotypes: 2

  Cell types:
    - Monocyte_Inf_mac
    - T_cell
    - Tissue-resident_mac
